<?php

// Alter all pages with necessary JS
function devdungeoncom_google_event_tracker_page_alter(&$page) {

	// Load global js event tracking functions
	drupal_add_js(drupal_get_path('module', 'devdungeoncom_google_event_tracker').'/js/global-ga-event-tracking.js', array('type' => 'file', 'scope' => 'footer', 'group' => JS_THEME ));
	
	// Custom Variables
	// User role
	global $user;
	if (in_array('Premium Member', $user->roles)) {
		$value = 'Premium Member';
	} else { // If not Premium
		$value = 'Prospect';
	}
	if ($user->uid == 0) { $value = 'Prospect'; }
	drupal_add_js(
		'var _gaq = _gaq || []; _gaq.push([\'_setCustomVar\', 1, \'memberType\', \''.$value.'\', 1]);',
		array('type' => 'inline', 'scope' => 'header', 'group' => JS_THEME)
	);
	
	// Data Layer
	// Pass promo_code from the session variable
	if (!empty($_SESSION['promo_code'])) {	
		drupal_add_js(
			'
			dataLayer = [{
				\'promoCode\': \''.$_SESSION['promo_code'].'\',
			}];
			',
			array('type' => 'inline', 'scope' => 'header', 'group' => JS_THEME )
		);
	}
	
}


// Hook Comment Presave
function devdungeoncom_google_event_tracker_comment_presave($comment) {
	$_SESSION['comment_presave_hooked'] = true; // Will trigger the JS include
}


// Hook User Insert
function devdungeoncom_google_event_tracker_user_insert(&$edit, $account, $category) {
	$_SESSION['user_insert_hooked'] = true;
}


// Add JS to page depending on which events were triggered
function devdungeoncom_google_event_tracker_preprocess_page($variables) {
	
	if (isset($_SESSION['comment_presave_hooked'])) {
		unset($_SESSION['comment_presave_hooked']);
		drupal_add_js(drupal_get_path('module', 'devdungeoncom_google_event_tracker').'/js/comment-insert.js', array('type' => 'file', 'scope' => 'footer', 'group' => JS_THEME ));
	}
	
	if (isset($_SESSION['user_insert_hooked'])) {
		unset($_SESSION['user_insert_hooked']);
		drupal_add_js(drupal_get_path('module', 'devdungeoncom_google_event_tracker').'/js/user-insert.js', array('type' => 'file', 'scope' => 'footer', 'group' => JS_THEME ));
	}

	/* // A better solution psuedo-code
	* foreach ($_SESSION['triggered_hooks'] as &$hook_name) {
	*    drupal_add_js( '/js/' . $hook_name . '.js' );
	*  }
	*  unset ($_SESSION['triggered_hooks'];
	*/
	
}
