all: build


build:
	g++ main.cpp -lsfml-graphics -lsfml-window -lsfml-system
	# -lsfml-{system,window,graphics,network,audio}

install:
	echo "Not yet implemented"

uninstall:
	echo "Not yet implemented"

clean:
	rm a.out

run:
	./a.out
	
