# A sample Guardfile
# More info at https://github.com/guard/guard#readme

# Install the gems with
# gem install guard guard-coffee guard-sass guard-uglify guard-livereload

# Generate a guard file with
# guard init

# Run guard with
# guard

# See what is installed with
# guard list

guard 'coffeescript', :input => 'src/coffee', :output => 'dest/js'

guard 'sass', :input => 'src/sass', :output => 'dest/css', :style => :compressed

guard 'uglify', :input => 'dest/js/test.js', :output => "dest/js/test.min.js" do
	watch (%r{dest/js/test.js})
end

guard 'livereload' do
  watch(%r{dest/js.+\.js})
  watch(%r{dest/css.+\.css})
  watch(%r{index.html})
end
