build:
	g++ main.cpp -std=gnu++11 -O2 -lp3framework -lpanda -lpandafx -lpandaexpress -lp3dtoolconfig -lp3dtool -lp3direct -I/usr/include/panda3d -L/usr/lib/x86_64-linux-gnu/panda3d
# https://docs.panda3d.org/1.10/cpp/introduction/running-your-program

