// Compile with
// gcc c_calling.c static_lib.o
// Automatically links the elf binary .o generated by
// the assembly compiler to resolve references

#include <stdio.h>

int main(int argc, char *argv[]) {

	// Define external from a separate library
	// Defined in something.o from a compiled 
	// assembly program
	extern print_hello();

	// Call external assembly function
	print_hello();
}
