#!/bin/bash

read -e -p "Output .key file: " -i "server.key" server_key
read -e -p "Output .csr file: " -i "server.csr" server_csr
read -e -p "Output .crt file: " -i "server.crt" server_crt
read -e -p "Output .pem file: " -i "server.pem" server_pem

#openssl generate 1024 RSA private key passphrased
openssl genrsa -out $server_key 1024 # add -des3 for passphrase

# openssl generate csr certificate signign request
openssl req -new -key $server_key -out $server_csr

# openssl remove passphrase from key
##openssl rsa -in server.key -out server.key

# Generate self-signed certificate
openssl x509 -req -days 365 -in $server_csr -signkey $server_key -out $server_crt

# Create pem
cat $server_key $server_crt > $server_pem
